# Generated by Django 4.0.2 on 2022-04-20 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20220222_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='Pedro', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='Perez', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='   Id único para este vestido en toda la tienda', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'En Mantención'), ('o', 'Arrendado'), ('a', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Disponibilidad', max_length=1),
        ),
    ]
