# Generated by Django 4.0.2 on 2022-05-06 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la Categoría (p. ej. Noche, Largo, Corto, Fiesta etc.)', max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(default='12875587-9', help_text='Ingrese RUT sin puntos y con digito verificador', max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Otro', help_text='Ingrese nombre y apellido de quien confeccionó el vestido', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Opcional', max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Opcional', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(help_text='Ingrese la talla', max_length=100)),
            ],
            options={
                'ordering': ['talla'],
            },
        ),
        migrations.CreateModel(
            name='Vestido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Sku único para este vestido particular en toda la tienda: Máximo 7 dígitos', max_length=7, unique=True)),
                ('nombre', models.CharField(help_text='Nombre que identifique el vestido fácilmente', max_length=200)),
                ('detalle', models.CharField(help_text='Ingrese una descripción del vestido', max_length=1000)),
                ('status', models.CharField(blank=True, choices=[('mantencion', 'mantención'), ('arrendado', 'arrendado'), ('disponible', 'disponible'), ('reservado', 'reservado')], default='mantencion', help_text='Disponibilidad del vestido', max_length=15)),
                ('categoria', models.ForeignKey(help_text='Seleccione una categoría para este vestido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria')),
                ('proveedor', models.ForeignKey(default='Otro', help_text='Opcional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.proveedor')),
                ('talla', models.ForeignKey(help_text='Seleccione una talla para este vestido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.talla')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(help_text='Fecha que reserva')),
                ('cliente', models.ForeignKey(help_text=' Ingrese Nombre de cliente que reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.cliente')),
                ('sku', models.ForeignKey(help_text='Ingrese el Sku del vestido que reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.vestido')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_arriendo', models.DateField(blank=True, help_text='Fecha inicio del arriendo', null=True)),
                ('fecha_a_devolver', models.DateField(blank=True, help_text='Fecha que debe devolver el vestido', null=True)),
                ('fecha_que_devolvio', models.DateField(blank=True, help_text='Fecha que devolvió el vestido', null=True)),
                ('valor_pagado', models.IntegerField(blank=True, help_text='Monto pagado por el arriendo', null=True)),
                ('fecha_de_pago', models.DateField(blank=True, help_text='Fecha que pagó el arriendo', null=True)),
                ('fecha_reservada', models.DateField(blank=True, help_text='Fecha fecha comienzo de reserva', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('mantencion', 'mantención'), ('arrendado', 'arrendado'), ('disponible', 'disponible'), ('reservado', 'reservado'), ('devuelto', 'devuelto')], default='mantencion', help_text='Disponibilidad del vestido', max_length=15)),
                ('cliente', models.ManyToManyField(help_text='Seleccione el cliente que arrienda', to='catalogo.Cliente')),
                ('sku', models.ForeignKey(help_text='VERIFIQUE el status del sku que identifica a este vestido particular', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.vestido')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
