# Generated by Django 4.0.2 on 2022-05-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='reservado',
            field=models.CharField(default='Reservado', max_length=10),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vestido',
            name='status',
            field=models.CharField(blank=True, choices=[('mantencion', 'Mantención'), ('arrendado', 'Arrendado'), ('disponible', 'Disponible'), ('reservado', 'Reservado')], default='mantencion', help_text='Disponibilidad del vestido', max_length=15),
        ),
    ]
