# Generated by Django 4.0.2 on 2022-05-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha_reservada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='reservado',
        ),
        migrations.AlterField(
            model_name='vestido',
            name='reservado',
            field=models.CharField(blank=True, choices=[('reservado', 'Reservado'), ('no reservado', 'No reservado')], default='no reservado', help_text='Disponibilidad del vestido', max_length=15),
        ),
    ]
