# Generated by Django 4.0.2 on 2022-04-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo_Devolucion',
            fields=[
                ('id', models.CharField(default='V000000', help_text='ID único para este vestido particular en toda la tienda', max_length=7, primary_key=True, serialize=False)),
                ('fecha_a_devolver', models.DateField(blank=True, help_text='Fecha que debe devolver el vestido', null=True)),
                ('devuelto', models.DateField(blank=True, help_text='Fecha cuando devolvió el vestido', null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'En mantención'), ('a', 'Arrendado'), ('d', 'Disponible'), ('r', 'Reservado')], default='a', help_text='Disponibilidad actualizada del vestido', max_length=1)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.cliente')),
                ('vestido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.catalogo')),
            ],
            options={
                'ordering': ['fecha_a_devolver'],
            },
        ),
        migrations.DeleteModel(
            name='Vestidos_para_arriendo',
        ),
    ]
