# Generated by Django 4.0.2 on 2022-05-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ManyToManyField(help_text='Seleccione el cliente que reserva', to='catalogo.Cliente'),
        ),
    ]
