# Generated by Django 4.0.2 on 2022-04-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='sku',
            field=models.ForeignKey(help_text='VERIFIQUE el status del sku que identifica a este vestido particular', on_delete=django.db.models.deletion.CASCADE, to='catalogo.vestido'),
        ),
    ]
