# Generated by Django 4.0.2 on 2022-04-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestido',
            name='status',
            field=models.CharField(blank=True, choices=[('mantencion', 'En mantención'), ('arrendado', 'Arrendado'), ('disponible', 'Disponible'), ('reservado', 'Reservado')], default='mantencion', help_text='Disponibilidad del vestido', max_length=15),
        ),
    ]
