# Generated by Django 4.0.2 on 2022-04-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_vestido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestido',
            name='cliente',
            field=models.ForeignKey(default='disponible', on_delete=django.db.models.deletion.CASCADE, to='catalogo.cliente'),
        ),
        migrations.AlterField(
            model_name='vestido',
            name='status',
            field=models.CharField(blank=True, choices=[('mantencion', 'mantención'), ('arrendado', 'arrendado'), ('disponible', 'disponible'), ('reservado', 'reservado')], default='mantencion', help_text='Disponibilidad del vestido', max_length=15),
        ),
    ]
