# Generated by Django 4.0.2 on 2022-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_arriendo_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='status',
            field=models.CharField(blank=True, choices=[('mantencion', 'mantención'), ('arrendado', 'arrendado'), ('disponible', 'disponible'), ('reservado', 'reservado')], default='mantencion', help_text='Disponibilidad del vestido', max_length=15),
        ),
    ]
