# Generated by Django 4.0.2 on 2022-04-21 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_name_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vestidos_para_arriendo',
            fields=[
                ('id', models.CharField(default='V000000', help_text='ID único para este vestido particular en toda la tienda', max_length=7, primary_key=True, serialize=False)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'En mantención'), ('o', 'Arrendado'), ('a', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Disponibilidad del vestido', max_length=1)),
            ],
            options={
                'ordering': ['fecha_devolucion'],
            },
        ),
        migrations.RenameModel(
            old_name='Vestido',
            new_name='Catalogo_Vestido',
        ),
        migrations.DeleteModel(
            name='Arriendo_vestido',
        ),
        migrations.AddField(
            model_name='vestidos_para_arriendo',
            name='vestido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.catalogo_vestido'),
        ),
    ]
