# Generated by Django 4.0.2 on 2022-05-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_fecha_reserva_reserva_fecha_reservada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestido',
            name='reservado',
            field=models.CharField(blank=True, choices=[('reservado', 'Reservado'), ('no_reservado', 'No reservado')], default='no_reservado', help_text='Disponibilidad del vestido', max_length=15),
        ),
    ]
