# Generated by Django 4.0.2 on 2022-05-06 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_reserva_cliente_reserva_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='fecha_de_pago',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='fecha_reservada',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='valor_pagado',
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.IntegerField(help_text='Ingrese el valor pagado')),
                ('fecha_de_pago', models.DateField(help_text='Ingrese fecha de pago')),
                ('comentario', models.CharField(max_length=300)),
                ('cliente', models.ManyToManyField(help_text='Ingrese cliente que pagó', to='catalogo.Cliente')),
                ('sku', models.ForeignKey(help_text='Ingrese el Sku del vestido que reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.vestido')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
