# Generated by Django 4.0.2 on 2022-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_vestido_devuelto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestido',
            name='fecha_a_devolver',
            field=models.DateField(blank=True, help_text='Fecha que debe devolver el vestido', null=True),
        ),
    ]
