# Generated by Django 4.0.2 on 2022-04-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_arriendo_devolucion_delete_vestidos_para_arriendo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arriendo_Devolucion',
            new_name='Arriendo_y_Devolucion',
        ),
        migrations.AlterModelOptions(
            name='arriendo_y_devolucion',
            options={'verbose_name': 'Arriendo_y_devolucion', 'verbose_name_plural': 'Arriendo_y_devoluciones'},
        ),
    ]
