# Generated by Django 4.0.2 on 2022-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_vestido_fecha_a_devolver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestido',
            name='devuelto',
            field=models.DateField(blank=True, help_text='Fecha cuando devolvió el vestido', null=True),
        ),
    ]
