# Generated by Django 4.0.2 on 2022-05-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_arriendo_fecha_de_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comentario',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
