# Generated by Django 4.0.2 on 2022-05-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_arriendo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='status',
            field=models.CharField(blank=True, choices=[('mantencion', 'mantención'), ('arrendado', 'arrendado'), ('disponible', 'disponible'), ('reservado', 'reservado'), ('devuelto', 'devuelto')], default='mantencion', help_text='Disponibilidad del vestido', max_length=15),
        ),
    ]
