# Generated by Django 4.0.2 on 2022-05-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_vestido_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestido',
            name='reservado',
            field=models.CharField(blank=True, choices=[('reservado', 'Reservado'), ('sin reserva', 'No_reservado')], default='sin reserva', help_text='Disponibilidad del vestido', max_length=15),
        ),
    ]
