# Generated by Django 4.0.2 on 2022-04-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_vestido_devuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.cliente'),
        ),
    ]
