# Generated by Django 4.0.2 on 2022-05-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_cliente_rut_alter_arriendo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
