# Generated by Django 4.0.2 on 2022-05-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_vestido_reservado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reservada']},
        ),
    ]
