# Generated by Django 4.0.2 on 2022-05-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default=7891253, max_length=12),
            preserve_default=False,
        ),
    ]
