# Generated by Django 4.0.2 on 2022-05-03 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_arriendo_creado_arriendo_modificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='creado',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
