# Generated by Django 4.0.2 on 2022-05-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_remove_arriendo_creado_arriendo_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='create',
            new_name='creado',
        ),
    ]
