# Generated by Django 4.0.2 on 2022-05-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_arriendo_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='borrower',
        ),
    ]
