# Generated by Django 4.0.2 on 2022-05-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_rename_create_arriendo_creado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arriendo',
            options={'ordering': ['sku']},
        ),
    ]
