# Generated by Django 4.0.2 on 2022-05-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_arriendo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arriendo',
            options={'ordering': ['status']},
        ),
    ]
