# Generated by Django 4.0.2 on 2022-05-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_arriendo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='fecha_reservada',
            field=models.DateField(blank=True, help_text='Fecha fecha comienzo de reserva', null=True),
        ),
    ]
